services:
  - type: web
    name: maybankpdf2json-web
    runtime: python
    runtimeVersion: "3.12"
    buildCommand: bash build.sh
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
    databaseId: postgres

databases:
  - name: postgres
    databaseName: maybankpdf2json
    user: maybankpdf2json
    plan: free
