# Generated by Django 4.2.29 on 2026-04-11 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=64)),
                ('statement_date', models.CharField(max_length=16)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('desc', models.TextField()),
                ('trans', models.FloatField()),
                ('bal', models.FloatField()),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.statement')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='statement',
            constraint=models.UniqueConstraint(fields=('account_number', 'statement_date'), name='uniq_account_statement_date_non_empty'),
        ),
        migrations.AddConstraint(
            model_name='statement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('account_number', ''), _negated=True), models.Q(('statement_date', ''), _negated=True)), name='statement_account_and_date_non_empty'),
        ),
    ]
