# Generated by Django 4.2.29 on 2026-04-07 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='statement',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='status',
        ),
    ]
