# Generated by Django 4.2.29 on 2026-04-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
