# Generated by Django 4.2.29 on 2026-04-05 07:30

from django.db import migrations, models


def dedupe_statement_dates(apps, schema_editor):
    Statement = apps.get_model("app", "Statement")

    dates = (
        Statement.objects.exclude(statement_date__isnull=True)
        .exclude(statement_date="")
        .values_list("statement_date", flat=True)
        .distinct()
    )

    for statement_date in dates:
        same_date = Statement.objects.filter(statement_date=statement_date)
        done_qs = same_date.filter(status="done").order_by("-uploaded_at", "-id")

        keep = done_qs.first()
        if keep is None:
            keep = same_date.order_by("-uploaded_at", "-id").first()

        if keep is not None:
            same_date.exclude(pk=keep.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_statement_filename"),
    ]

    operations = [
        migrations.RunPython(dedupe_statement_dates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="statement",
            constraint=models.UniqueConstraint(
                condition=models.Q(statement_date__isnull=False)
                & ~models.Q(statement_date=""),
                fields=("statement_date",),
                name="uniq_statement_date_non_empty",
            ),
        ),
    ]
