# Generated by Django 4.2.29 on 2026-04-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='statement',
            name='uniq_statement_date_non_empty',
        ),
        migrations.AddConstraint(
            model_name='statement',
            constraint=models.UniqueConstraint(condition=models.Q(('account_number__isnull', False), models.Q(('account_number', ''), _negated=True), ('statement_date__isnull', False), models.Q(('statement_date', ''), _negated=True)), fields=('account_number', 'statement_date'), name='uniq_account_statement_date_non_empty'),
        ),
    ]
