# Generated by Django 4.2.29 on 2026-04-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_statement_uniq_statement_date_non_empty_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='statement',
            name='uniq_account_statement_date_non_empty',
        ),
        migrations.AlterField(
            model_name='statement',
            name='account_number',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='statement',
            name='statement_date',
            field=models.CharField(max_length=16),
        ),
        migrations.AddConstraint(
            model_name='statement',
            constraint=models.UniqueConstraint(fields=('account_number', 'statement_date'), name='uniq_account_statement_date_non_empty'),
        ),
        migrations.AddConstraint(
            model_name='statement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('account_number', ''), _negated=True), models.Q(('statement_date', ''), _negated=True)), name='statement_account_and_date_non_empty'),
        ),
    ]
